KunstmaanSitemapBundle:
    resource: "@KunstmaanSitemapBundle/Resources/config/routing.yml"
    # If your site is not multi language, remove the "{_locale}/" part of prefix and requirements
    prefix:   /
    requirements:
        _locale: "%kunstmaan_admin.required_locales%"
