<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    FOS\HttpCacheBundle\FOSHttpCacheBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    FOS\UserBundle\FOSUserBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle::class => ['all' => true],
    Symfony\Bundle\AclBundle\AclBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Kunstmaan\UtilitiesBundle\KunstmaanUtilitiesBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Kunstmaan\AdminBundle\KunstmaanAdminBundle::class => ['all' => true],
    Kunstmaan\AdminListBundle\KunstmaanAdminListBundle::class => ['all' => true],
    Kunstmaan\NodeBundle\KunstmaanNodeBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Kunstmaan\ConfigBundle\KunstmaanConfigBundle::class => ['all' => true],
    Kunstmaan\DashboardBundle\KunstmaanDashboardBundle::class => ['all' => true],
    Kunstmaan\SearchBundle\KunstmaanSearchBundle::class => ['all' => true],
    Kunstmaan\PagePartBundle\KunstmaanPagePartBundle::class => ['all' => true],
    Kunstmaan\NodeSearchBundle\KunstmaanNodeSearchBundle::class => ['all' => true],
    Kunstmaan\RedirectBundle\KunstmaanRedirectBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    Kunstmaan\MediaBundle\KunstmaanMediaBundle::class => ['all' => true],
    Kunstmaan\SeoBundle\KunstmaanSeoBundle::class => ['all' => true],
    Kunstmaan\SitemapBundle\KunstmaanSitemapBundle::class => ['all' => true],
    Kunstmaan\TranslatorBundle\KunstmaanTranslatorBundle::class => ['all' => true],
    Kunstmaan\UserManagementBundle\KunstmaanUserManagementBundle::class => ['all' => true],
    Sentry\SentryBundle\SentryBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Kunstmaan\MenuBundle\KunstmaanMenuBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Kunstmaan\FixturesBundle\KunstmaanFixturesBundle::class => ['dev' => true, 'test' => true],
    Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle::class => ['dev' => true, 'test' => true],
    Kunstmaan\MediaPagePartBundle\KunstmaanMediaPagePartBundle::class => ['all' => true],
    Kunstmaan\FormBundle\KunstmaanFormBundle::class => ['all' => true],
    Kunstmaan\ArticleBundle\KunstmaanArticleBundle::class => ['all' => true],
    Kunstmaan\GeneratorBundle\KunstmaanGeneratorBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
];
